// Stores all routines of exercises

const routineStore = {
  WARMUP_LIGHT: [
    'INTRO_WARMUP_LIGHT',
    'TOUCH_TOES_EASY_INIT', 
    'TOUCH_TOES_EASY',
    'ELBOW_PULL_INIT',
    'ELBOW_PULL',
    'LEG_RAISES_INIT',
    'LEG_RAISES',
    'ARCHING_ARM_STRETCH_INIT',
    'ARCHING_ARM_STRETCH',
    'HEAL_DOWN_CALF_STRETCH_INIT',
    'HEAL_DOWN_CALF_STRETCH',
    'END'
  ],
  WARMUP_MEDIUM: [
    'INTRO_WARMUP_MEDIUM',
    'TOUCH_TOES_EASY_INIT', 
    'TOUCH_TOES_EASY',
    'ELBOW_PULL_INIT',
    'ELBOW_PULL',
    'LEG_RAISES_INIT',
    'LEG_RAISES',
    'ARCHING_ARM_STRETCH_INIT',
    'ARCHING_ARM_STRETCH',
    'HEAL_DOWN_CALF_STRETCH_INIT',
    'HEAL_DOWN_CALF_STRETCH',
    'BUTTERFLY_GROIN_STRETCH_INIT',
    'BUTTERFLY_GROIN_STRETCH',
    'DOUBLE_HEAL_LIFTS_INIT', 
    'DOUBLE_HEAL_LIFTS',
    'END'
  ],
  WARMUP_HARD: [
    'INTRO_WARMUP_HARD',
    'TOUCH_TOES_EASY_INIT', 
    'TOUCH_TOES_EASY',
    'ELBOW_PULL_INIT',
    'ELBOW_PULL',
    'LEG_RAISES_INIT',
    'LEG_RAISES',
    'ARCHING_ARM_STRETCH_INIT',
    'ARCHING_ARM_STRETCH',
    'HEAL_DOWN_CALF_STRETCH_INIT',
    'HEAL_DOWN_CALF_STRETCH',
    'BUTTERFLY_GROIN_STRETCH_INIT',
    'BUTTERFLY_GROIN_STRETCH',
    'DOUBLE_HEAL_LIFTS_INIT', 
    'DOUBLE_HEAL_LIFTS',
    'SINGLE_HEAL_LIFTS_INIT',
    'SINGLE_HEAL_LIFTS',
    'END'
  ], 
  WALK_LIGHT: [
    'INTRO_WALK_LIGHT',
    'DOUBLE_HEAL_LIFTS_INIT', 
    'DOUBLE_HEAL_LIFTS',
    'TOUCH_TOES_EASY_INIT',
    'TOUCH_TOES_EASY',
    'END'
  ],
  WALK_MEDIUM: [
    'INTRO_WALK_LIGHT',
    'HEAL_DOWN_CALF_STRETCH_INIT',
    'HEAL_DOWN_CALF_STRETCH',
    'DOUBLE_HEAL_LIFTS_INIT', 
    'DOUBLE_HEAL_LIFTS',
    'TOUCH_TOES_EASY_INIT',
    'TOUCH_TOES_EASY',
    'END'
  ],
  WALK_HARD: [
    'INTRO_WALK_LIGHT',
    'HEAL_DOWN_CALF_STRETCH_INIT',
    'HEAL_DOWN_CALF_STRETCH',
    'DOUBLE_HEAL_LIFTS_INIT', 
    'DOUBLE_HEAL_LIFTS',
    'SINGLE_HEAL_LIFTS_INIT',
    'SINGLE_HEAL_LIFTS',
    'TOUCH_TOES_EASY_INIT',
    'TOUCH_TOES_EASY',
    'END'
  ], 
  JOG_LIGHT: [
    'INTRO_JOG_LIGHT',
    'HEAL_DOWN_CALF_STRETCH_INIT',
    'HEAL_DOWN_CALF_STRETCH',
    'DOUBLE_HEAL_LIFTS_INIT', 
    'DOUBLE_HEAL_LIFTS',
    'TOUCH_TOES_EASY_INIT',
    'TOUCH_TOES_EASY',
    'END'
  ],
  JOG_MEDIUM: [
    'INTRO_JOG_LIGHT',
    'SINGLE_HEAL_LIFTS_INIT',
    'SINGLE_HEAL_LIFTS',
    'LEG_RAISES_INIT',
    'LEG_RAISES',
    'END'
  ],
  JOG_HARD: [
    'INTRO_JOG_LIGHT',
    'DOUBLE_HEAL_LIFTS_INIT', 
    'DOUBLE_HEAL_LIFTS',
    'SINGLE_HEAL_LIFTS_INIT',
    'SINGLE_HEAL_LIFTS',
    'BOTTOM_LIFTS_INIT',
    'BOTTOM_LIFTS',
    'BUTTERFLY_GROIN_STRETCH_INIT',
    'BUTTERFLY_GROIN_STRETCH',
    'END'
  ],
  SWIM_LIGHT: [
    'INTRO_SWIM_LIGHT',
    'ELBOW_PULL_INIT',
    'ELBOW_PULL',
    'ARCHING_ARM_STRETCH_INIT',
    'ARCHING_ARM_STRETCH',
    'BUTTERFLY_GROIN_STRETCH_INIT',
    'BUTTERFLY_GROIN_STRETCH',
    'END'
  ],
  SWIM_MEDIUM: [
    'INTRO_SWIM_LIGHT',
    'ELBOW_PULL_INIT',
    'ELBOW_PULL',
    'BUTTERFLY_GROIN_STRETCH_INIT',
    'BUTTERFLY_GROIN_STRETCH',
    'TOUCH_TOES_EASY_INIT',
    'TOUCH_TOES_EASY',
    'LEG_RAISES_INIT',
    'LEG_RAISES',
    'END'
  ],
  SWIM_HARD: [
    'INTRO_SWIM_LIGHT',
    'ELBOW_PULL_INIT',
    'ELBOW_PULL',
    'BUTTERFLY_GROIN_STRETCH_INIT',
    'BUTTERFLY_GROIN_STRETCH',
    'DOUBLE_HEAL_LIFTS_INIT', 
    'DOUBLE_HEAL_LIFTS',
    'TOUCH_TOES_EASY_INIT',
    'TOUCH_TOES_EASY',
    'BOTTOM_LIFTS_INIT',
    'BOTTOM_LIFTS',
    'LEG_RAISES_INIT',
    'LEG_RAISES',
    'END'
  ],
  RUN_LIGHT: [
    'INTRO_RUN_LIGHT',
    'HEAL_DOWN_CALF_STRETCH_INIT',
    'HEAL_DOWN_CALF_STRETCH',
    'DOUBLE_HEAL_LIFTS_INIT', 
    'DOUBLE_HEAL_LIFTS',
    'TOUCH_TOES_EASY_INIT',
    'TOUCH_TOES_EASY',
    'END'
  ],
  RUN_MEDIUM: [
    'CLOSE_SESSION_NOT_READY'
  ],
  RUN_HARD: [
    'CLOSE_SESSION_NOT_READY'
  ],
  SOCCER_LIGHT: [
    'INTRO_SOCCER_LIGHT',
    'HEAL_DOWN_CALF_STRETCH_INIT',
    'HEAL_DOWN_CALF_STRETCH',
    'DOUBLE_HEAL_LIFTS_INIT', 
    'DOUBLE_HEAL_LIFTS',
    'TOUCH_TOES_EASY_INIT',
    'TOUCH_TOES_EASY',
    'END'
  ],
  SOCCER_MEDIUM: [
    'INTRO_SOCCER_MEDIUM',
    'HEAL_DOWN_CALF_STRETCH_INIT',
    'HEAL_DOWN_CALF_STRETCH',
    'DOUBLE_HEAL_LIFTS_INIT', 
    'DOUBLE_HEAL_LIFTS',
    'TOUCH_TOES_EASY_INIT',
    'TOUCH_TOES_EASY',
    'BUTTERFLY_GROIN_STRETCH_INIT',
    'BUTTERFLY_GROIN_STRETCH',
    'END'
  ],
  SOCCER_HARD: [
    'INTRO_SOCCER_HARD',
    'HEAL_DOWN_CALF_STRETCH_INIT',
    'HEAL_DOWN_CALF_STRETCH',
    'DOUBLE_HEAL_LIFTS_INIT', 
    'DOUBLE_HEAL_LIFTS',
    'SINGLE_HEAL_LIFTS_INIT',
    'SINGLE_HEAL_LIFTS',
    'TOUCH_TOES_EASY_INIT',
    'TOUCH_TOES_EASY',
    'BUTTERFLY_GROIN_STRETCH_INIT',
    'BUTTERFLY_GROIN_STRETCH',
    'END'
  ],
  TENNIS_LIGHT: [
    'CLOSE_SESSION_NOT_READY'
  ],
  TENNIS_MEDIUM: [
    'CLOSE_SESSION_NOT_READY'
  ],
  WEIGHTS_LIGHT: [
    'CLOSE_SESSION_NOT_READY'
  ],
  WEIGHTS_MEDIUM: [
    'CLOSE_SESSION_NOT_READY'
  ],
  WEIGHTS_HARD: [
    'CLOSE_SESSION_NOT_READY'
  ],
  TENNIS_HARD: [
    'CLOSE_SESSION_NOT_READY'
  ],
  WEGIHTS_LIGHT: [
    'CLOSE_SESSION_NOT_READY'
  ],
  WEGIHTS_MEDIUM: [
    'CLOSE_SESSION_NOT_READY'
  ],
  WEGIHTS_HARD: [
    'CLOSE_SESSION_NOT_READY'
  ],
  GOLF_LIGHT: [
    'CLOSE_SESSION_NOT_READY'
  ],
  GOLF_MEDIUM: [
    'CLOSE_SESSION_NOT_READY'
  ],
  GOLF_HARD: [
    'CLOSE_SESSION_NOT_READY'
  ],
  BASKETBALL_LIGHT: [
    'CLOSE_SESSION_NOT_READY'
  ],
  BASKETBALL_MEDIUM: [
    'CLOSE_SESSION_NOT_READY'
  ],
  BASKETBALL_HARD: [
    'CLOSE_SESSION_NOT_READY'
  ],
  CRICKET_LIGHT: [
    'CLOSE_SESSION_NOT_READY'
  ],
  CRICKET_MEDIUM: [
    'CLOSE_SESSION_NOT_READY'
  ],
  CRICKET_HARD: [
    'CLOSE_SESSION_NOT_READY'
  ],
  BOX_LIGHT: [
    'CLOSE_SESSION_NOT_READY'
  ],
  BOX_MEDIUM: [
    'CLOSE_SESSION_NOT_READY'
  ],
  BOX_HARD: [
    'CLOSE_SESSION_NOT_READY'
  ],
  KAYAK_LIGHT: [
    'CLOSE_SESSION_NOT_READY'
  ],
  KAYAK_MEDIUM: [
    'CLOSE_SESSION_NOT_READY'
  ],
  KAYAK_HARD: [
    'CLOSE_SESSION_NOT_READY'
  ],
  SURF_LIGHT: [
    'CLOSE_SESSION_NOT_READY'
  ],
  SURF_MEDIUM: [
    'CLOSE_SESSION_NOT_READY'
  ],
  SURF_HARD: [
    'CLOSE_SESSION_NOT_READY'
  ],
  FRISBEE_LIGHT: [
    'CLOSE_SESSION_NOT_READY'
  ],
  FRISBEE_MEDIUM: [
    'CLOSE_SESSION_NOT_READY'
  ],
  FRISBEE_HARD: [
    'CLOSE_SESSION_NOT_READY'
  ],
  CYCLE_LIGHT: [
    'CLOSE_SESSION_NOT_READY'
  ],
  CYCLE_MEDIUM: [
    'CLOSE_SESSION_NOT_READY'
  ],
  CYCLE_HARD: [
    'CLOSE_SESSION_NOT_READY'
  ],
  DANCE_LIGHT: [
    'CLOSE_SESSION_NOT_READY'
  ],
  DANCE_MEDIUM: [
    'CLOSE_SESSION_NOT_READY'
  ],
  DANCE_HARD: [
    'CLOSE_SESSION_NOT_READY'
  ],
  GARDEN_LIGHT: [
    'CLOSE_SESSION_NOT_READY'
  ],
  GARDEN_MEDIUM: [
    'CLOSE_SESSION_NOT_READY'
  ],
  GARDEN_HARD: [
    'CLOSE_SESSION_NOT_READY'
  ],
  NETBALL_LIGHT: [
    'CLOSE_SESSION_NOT_READY'
  ],
  NETBALL_MEDIUM: [
    'CLOSE_SESSION_NOT_READY'
  ],
  NETBALL_HARD: [
    'CLOSE_SESSION_NOT_READY'
  ],
  YOGA_LIGHT: [
    'CLOSE_SESSION_NOT_READY'
  ],
  YOGA_MEDIUM: [
    'CLOSE_SESSION_NOT_READY'
  ],
  YOGA_HARD: [
    'CLOSE_SESSION_NOT_READY'
  ],
  PADDLEBOARD_LIGHT: [
    'CLOSE_SESSION_NOT_READY'
  ],
  PADDLEBOARD_MEDIUM: [
    'CLOSE_SESSION_NOT_READY'
  ],
  PADDLEBOARD_HARD: [
    'CLOSE_SESSION_NOT_READY'
  ],
  HIKE_LIGHT: [
    'CLOSE_SESSION_NOT_READY'
  ],
  HIKE_MEDIUM: [
    'CLOSE_SESSION_NOT_READY'
  ],
  HIKE_HARD: [
    'CLOSE_SESSION_NOT_READY'
  ],
  CLIMBING_LIGHT: [
    'CLOSE_SESSION_NOT_READY'
  ],
  CLIMBING_MEDIUM: [
    'CLOSE_SESSION_NOT_READY'
  ],
  CLIMBING_HARD: [
    'CLOSE_SESSION_NOT_READY'
  ],
  CROSSTRAIN_LIGHT: [
    'CLOSE_SESSION_NOT_READY'
  ],
  CROSSTRAIN_MEDIUM: [
    'CLOSE_SESSION_NOT_READY'
  ],
  CROSSTRAIN_HARD: [
    'CLOSE_SESSION_NOT_READY'
  ],
  HORSERIDE_LIGHT: [
    'CLOSE_SESSION_NOT_READY'
  ],
  HORSERIDE_MEDIUM: [
    'CLOSE_SESSION_NOT_READY'
  ],
  HORSERIDE_HARD: [
    'CLOSE_SESSION_NOT_READY'
  ],
  SKATING_LIGHT: [
    'CLOSE_SESSION_NOT_READY'
  ],
  SKATING_MEDIUM: [
    'CLOSE_SESSION_NOT_READY'
  ],
  SKATING_HARD: [
    'CLOSE_SESSION_NOT_READY'
  ],
  ARMS: [
    'CLOSE_SESSION_NOT_READY'
  ],
  LOWER_LEGS: [
    'CLOSE_SESSION_NOT_READY'
  ],
  UPPER_LEGS: [
    'CLOSE_SESSION_NOT_READY'
  ],
  STOMACH: [
    'CLOSE_SESSION_NOT_READY'
  ],
  CORE_STRENGTH: [
    'CLOSE_SESSION_NOT_READY'
  ],
};

module.exports = routineStore;