// Stores all routines of exercises

const routineStore = {
  WARMUP_LIGHT: [
    'INTRO_WARMUP_LIGHT',
    'TOUCH_TOES_EASY_INIT', 
    'TOUCH_TOES_EASY',
    'ELBOW_PULL_INIT',
    'ELBOW_PULL',
    'LEG_RAISES_INIT',
    'LEG_RAISES',
    'ARCHING_ARM_STRETCH_INIT',
    'ARCHING_ARM_STRETCH',
    'HEAL_DOWN_CALF_STRETCH_INIT',
    'HEAL_DOWN_CALF_STRETCH',
    'END'
  ],
  WARMUP_MEDIUM: [
    'INTRO_WARMUP_MEDIUM',
    'TOUCH_TOES_EASY_INIT', 
    'TOUCH_TOES_EASY',
    'ELBOW_PULL_INIT',
    'ELBOW_PULL',
    'LEG_RAISES_INIT',
    'LEG_RAISES',
    'ARCHING_ARM_STRETCH_INIT',
    'ARCHING_ARM_STRETCH',
    'HEAL_DOWN_CALF_STRETCH_INIT',
    'HEAL_DOWN_CALF_STRETCH',
    'BUTTERFLY_GROIN_STRETCH_INIT',
    'BUTTERFLY_GROIN_STRETCH',
    'DOUBLE_HEAL_LIFTS_INIT', 
    'DOUBLE_HEAL_LIFTS',
    'END'
  ],
  WARMUP_HARD: [
    'INTRO_WARMUP_HARD',
    'TOUCH_TOES_EASY_INIT', 
    'TOUCH_TOES_EASY',
    'ELBOW_PULL_INIT',
    'ELBOW_PULL',
    'LEG_RAISES_INIT',
    'LEG_RAISES',
    'ARCHING_ARM_STRETCH_INIT',
    'ARCHING_ARM_STRETCH',
    'HEAL_DOWN_CALF_STRETCH_INIT',
    'HEAL_DOWN_CALF_STRETCH',
    'BUTTERFLY_GROIN_STRETCH_INIT',
    'BUTTERFLY_GROIN_STRETCH',
    'DOUBLE_HEAL_LIFTS_INIT', 
    'DOUBLE_HEAL_LIFTS',
    'SINGLE_HEAL_LIFTS_INIT',
    'SINGLE_HEAL_LIFTS',
    'END'
  ],
  WALK_LIGHT: [
    'INTRO_WALK_LIGHT',
    'DOUBLE_HEAL_LIFTS_INIT', 
    'DOUBLE_HEAL_LIFTS',
    'TOUCH_TOES_EASY_INIT',
    'TOUCH_TOES_EASY',
    'END'
  ],
  WALK_MEDIUM: [
    'INTRO_WALK_LIGHT',
    'HEAL_DOWN_CALF_STRETCH_INIT',
    'HEAL_DOWN_CALF_STRETCH',
    'DOUBLE_HEAL_LIFTS_INIT', 
    'DOUBLE_HEAL_LIFTS',
    'TOUCH_TOES_EASY_INIT',
    'TOUCH_TOES_EASY',
    'END'
  ],
  WALK_HARD: [
    'INTRO_WALK_LIGHT',
    'HEAL_DOWN_CALF_STRETCH_INIT',
    'HEAL_DOWN_CALF_STRETCH',
    'DOUBLE_HEAL_LIFTS_INIT', 
    'DOUBLE_HEAL_LIFTS',
    'SINGLE_HEAL_LIFTS_INIT',
    'SINGLE_HEAL_LIFTS',
    'TOUCH_TOES_EASY_INIT',
    'TOUCH_TOES_EASY',
    'END'
  ],
  JOG_LIGHT: [
    'INTRO_JOG_LIGHT',
    'HEAL_DOWN_CALF_STRETCH_INIT',
    'HEAL_DOWN_CALF_STRETCH',
    'DOUBLE_HEAL_LIFTS_INIT', 
    'DOUBLE_HEAL_LIFTS',
    'TOUCH_TOES_EASY_INIT',
    'TOUCH_TOES_EASY',
    'END'
  ],
  JOG_MEDIUM: [
    'INTRO_JOG_LIGHT',
    'SINGLE_HEAL_LIFTS_INIT',
    'SINGLE_HEAL_LIFTS',
    'LEG_RAISES_INIT',
    'LEG_RAISES',
    'END'
  ],
  JOG_HARD: [
    'INTRO_JOG_LIGHT',
    'DOUBLE_HEAL_LIFTS_INIT', 
    'DOUBLE_HEAL_LIFTS',
    'SINGLE_HEAL_LIFTS_INIT',
    'SINGLE_HEAL_LIFTS',
    'BOTTOM_LIFTS_INIT',
    'BOTTOM_LIFTS',
    'BUTTERFLY_GROIN_STRETCH_INIT',
    'BUTTERFLY_GROIN_STRETCH',
    'END'
  ],
  SWIM_LIGHT: [
    'INTRO_SWIM_LIGHT',
    'ELBOW_PULL_INIT',
    'ELBOW_PULL',
    'ARCHING_ARM_STRETCH_INIT',
    'ARCHING_ARM_STRETCH',
    'BUTTERFLY_GROIN_STRETCH_INIT',
    'BUTTERFLY_GROIN_STRETCH',
    'END'
  ],
  SWIM_MEDIUM: [
    'INTRO_SWIM_LIGHT',
    'ELBOW_PULL_INIT',
    'ELBOW_PULL',
    'BUTTERFLY_GROIN_STRETCH_INIT',
    'BUTTERFLY_GROIN_STRETCH',
    'TOUCH_TOES_EASY_INIT',
    'TOUCH_TOES_EASY',
    'LEG_RAISES_INIT',
    'LEG_RAISES',
    'END'
  ],
  SWIM_HARD: [
    'INTRO_SWIM_LIGHT',
    'ELBOW_PULL_INIT',
    'ELBOW_PULL',
    'BUTTERFLY_GROIN_STRETCH_INIT',
    'BUTTERFLY_GROIN_STRETCH',
    'DOUBLE_HEAL_LIFTS_INIT', 
    'DOUBLE_HEAL_LIFTS',
    'TOUCH_TOES_EASY_INIT',
    'TOUCH_TOES_EASY',
    'BOTTOM_LIFTS_INIT',
    'BOTTOM_LIFTS',
    'LEG_RAISES_INIT',
    'LEG_RAISES',
    'END'
  ],
  RUN_LIGHT: [
    'INTRO_RUN_LIGHT',
    'HEAL_DOWN_CALF_STRETCH_INIT',
    'HEAL_DOWN_CALF_STRETCH',
    'DOUBLE_HEAL_LIFTS_INIT', 
    'DOUBLE_HEAL_LIFTS',
    'TOUCH_TOES_EASY_INIT',
    'TOUCH_TOES_EASY',
    'END'
  ],
  RUN_MEDIUM: [
    'INTRO_RUN_MEDIUM'
  ],
  RUN_HARD: [
    'INTRO_RUN_HARD'
  ],
  SOCCER_LIGHT: [
    'INTRO_SOCCER_LIGHT',
    'HEAL_DOWN_CALF_STRETCH_INIT',
    'HEAL_DOWN_CALF_STRETCH',
    'DOUBLE_HEAL_LIFTS_INIT', 
    'DOUBLE_HEAL_LIFTS',
    'TOUCH_TOES_EASY_INIT',
    'TOUCH_TOES_EASY',
    'END'
  ],
  SOCCER_MEDIUM: [
    'INTRO_SOCCER_MEDIUM',
    'HEAL_DOWN_CALF_STRETCH_INIT',
    'HEAL_DOWN_CALF_STRETCH',
    'DOUBLE_HEAL_LIFTS_INIT', 
    'DOUBLE_HEAL_LIFTS',
    'TOUCH_TOES_EASY_INIT',
    'TOUCH_TOES_EASY',
    'BUTTERFLY_GROIN_STRETCH_INIT',
    'BUTTERFLY_GROIN_STRETCH',
    'END'
  ],
  SOCCER_HARD: [
    'INTRO_SOCCER_HARD',
    'HEAL_DOWN_CALF_STRETCH_INIT',
    'HEAL_DOWN_CALF_STRETCH',
    'DOUBLE_HEAL_LIFTS_INIT', 
    'DOUBLE_HEAL_LIFTS',
    'SINGLE_HEAL_LIFTS_INIT',
    'SINGLE_HEAL_LIFTS',
    'TOUCH_TOES_EASY_INIT',
    'TOUCH_TOES_EASY',
    'BUTTERFLY_GROIN_STRETCH_INIT',
    'BUTTERFLY_GROIN_STRETCH',
    'END'
  ],
  TENNIS_LIGHT: [
    'INTRO_TENNIS_LIGHT',
    'END'
  ],
  TENNIS_MEDIUM: [
    'INTRO_TENNIS_LIGHT',
    'END'
  ],
  WEIGHTS_LIGHT: [
    'INTRO_WEIGHTS_LIGHT',
    'END'
  ],
  WEIGHTS_MEDIUM: [
    'INTRO_WEIGHTS_LIGHT',
    'END'
  ],
  WEIGHTS_HARD: [
    'INTRO_WEIGHTS_LIGHT',
    'END'
  ],
  TENNIS_HARD: [
    'INTRO_TENNIS_LIGHT',
    'END'
  ],
  WEGIHTS_LIGHT: [
    'INTRO_WEGIHTS_LIGHT',
    'END'
  ],
  WEGIHTS_MEDIUM: [
    'INTRO_WEGIHTS_LIGHT',
    'END'
  ],
  WEGIHTS_HARD: [
    'INTRO_WEGIHTS_LIGHT',
    'END'
  ],
  GOLF_LIGHT: [
    'INTRO_GOLF_LIGHT',
    'END'
  ],
  GOLF_MEDIUM: [
    'INTRO_GOLF_LIGHT',
    'END'
  ],
  GOLF_HARD: [
    'INTRO_GOLF_LIGHT',
    'END'
  ],
  BASKETBALL_LIGHT: [
    'INTRO_BASKETBALL_LIGHT',
    'END'
  ],
  BASKETBALL_MEDIUM: [
    'INTRO_BASKETBALL_LIGHT',
    'END'
  ],
  BASKETBALL_HARD: [
    'INTRO_BASKETBALL_LIGHT',
    'END'
  ],
  CRICKET_LIGHT: [
    'INTRO_CRICKET_LIGHT',
    'END'
  ],
  CRICKET_MEDIUM: [
    'INTRO_CRICKET_LIGHT',
    'END'
  ],
  CRICKET_HARD: [
    'INTRO_CRICKET_LIGHT',
    'END'
  ],
  BOX_LIGHT: [
    'INTRO_BOX_LIGHT',
    'END'
  ],
  BOX_MEDIUM: [
    'INTRO_BOX_LIGHT',
    'END'
  ],
  BOX_HARD: [
    'INTRO_BOX_LIGHT',
    'END'
  ],
  KAYAK_LIGHT: [
    'INTRO_KAYAK_LIGHT',
    'END'
  ],
  KAYAK_MEDIUM: [
    'INTRO_KAYAK_LIGHT',
    'END'
  ],
  KAYAK_HARD: [
    'INTRO_KAYAK_LIGHT',
    'END'
  ],
  SURF_LIGHT: [
    'INTRO_SURF_LIGHT',
    'END'
  ],
  SURF_MEDIUM: [
    'INTRO_SURF_LIGHT',
    'END'
  ],
  SURF_HARD: [
    'INTRO_SURF_LIGHT',
    'END'
  ],
  FRISBEE_LIGHT: [
    'INTRO_FRISBEE_LIGHT',
    'END'
  ],
  FRISBEE_MEDIUM: [
    'INTRO_FRISBEE_LIGHT',
    'END'
  ],
  FRISBEE_HARD: [
    'INTRO_FRISBEE_LIGHT',
    'END'
  ],
  CYCLE_LIGHT: [
    'INTRO_CYCLE_LIGHT',
    'END'
  ],
  CYCLE_MEDIUM: [
    'INTRO_CYCLE_LIGHT',
    'END'
  ],
  CYCLE_HARD: [
    'INTRO_CYCLE_LIGHT',
    'END'
  ],
  DANCE_LIGHT: [
    'INTRO_DANCE_LIGHT',
    'END'
  ],
  DANCE_MEDIUM: [
    'INTRO_DANCE_LIGHT',
    'END'
  ],
  DANCE_HARD: [
    'INTRO_DANCE_LIGHT',
    'END'
  ],
  GARDEN_LIGHT: [
    'INTRO_GARDEN_LIGHT',
    'END'
  ],
  GARDEN_MEDIUM: [
    'INTRO_GARDEN_LIGHT',
    'END'
  ],
  GARDEN_HARD: [
    'INTRO_GARDEN_LIGHT',
    'END'
  ],
  NETBALL_LIGHT: [
    'INTRO_NETBALL_LIGHT',
    'END'
  ],
  NETBALL_MEDIUM: [
    'INTRO_NETBALL_LIGHT',
    'END'
  ],
  NETBALL_HARD: [
    'INTRO_NETBALL_LIGHT',
    'END'
  ],
  YOGA_LIGHT: [
    'INTRO_YOGA_LIGHT',
    'END'
  ],
  YOGA_MEDIUM: [
    'INTRO_YOGA_LIGHT',
    'END'
  ],
  YOGA_HARD: [
    'INTRO_YOGA_LIGHT',
    'END'
  ],
  PADDLEBOARD_LIGHT: [
    'INTRO_PADDLE_BOARD_LIGHT',
    'END'
  ],
  PADDLEBOARD_MEDIUM: [
    'INTRO_PADDLE_BOARD_LIGHT',
    'END'
  ],
  PADDLEBOARD_HARD: [
    'INTRO_PADDLE_BOARD_LIGHT',
    'END'
  ],
  HIKE_LIGHT: [
    'INTRO_HIKE_LIGHT',
    'END'
  ],
  HIKE_MEDIUM: [
    'INTRO_HIKE_LIGHT',
    'END'
  ],
  HIKE_HARD: [
    'INTRO_HIKE_LIGHT',
    'END'
  ],
  CLIMBING_LIGHT: [
    'INTRO_CLIMBING_LIGHT',
    'END'
  ],
  CLIMBING_MEDIUM: [
    'INTRO_CLIMBING_LIGHT',
    'END'
  ],
  CLIMBING_HARD: [
    'INTRO_CLIMBING_LIGHT',
    'END'
  ],
  CROSSTRAIN_LIGHT: [
    'INTRO_CROSSTRAIN_LIGHT',
    'END'
  ],
  CROSSTRAIN_MEDIUM: [
    'INTRO_CROSSTRAIN_LIGHT',
    'END'
  ],
  CROSSTRAIN_HARD: [
    'INTRO_CROSSTRAIN_LIGHT',
    'END'
  ],
  HORSERIDE_LIGHT: [
    'INTRO_HORSERIDE_LIGHT',
    'END'
  ],
  HORSERIDE_MEDIUM: [
    'INTRO_HORSERIDE_LIGHT',
    'END'
  ],
  HORSERIDE_HARD: [
    'INTRO_HORSERIDE_LIGHT',
    'END'
  ],
  SKATING_LIGHT: [
    'INTRO_SKATING_LIGHT',
    'END'
  ],
  SKATING_MEDIUM: [
    'INTRO_SKATING_LIGHT',
    'END'
  ],
  SKATING_HARD: [
    'INTRO_SKATING_LIGHT',
    'END'
  ],
  ARMS: [
    'INTRO_ARMS',
    'END'
  ],
  LOWER_LEGS: [
    'INTRO_LOWER_LEGS',
    'END'
  ],
  UPPER_LEGS: [
    'INTRO_UPPER_LEGS',
    'END'
  ],
  STOMACH: [
    'INTRO_STOMACH',
    'END'
  ],
  CORE_STRENGTH: [
    'INTRO_CORE_STRENGTH',
    'END'
  ],
};

module.exports = routineStore;