// Stores all routines of exercises

const routineStore = {
  JOG_LIGHT: [
    'INTRO_JOG_LIGHT',
    'HEAL_DOWN_CALF_STRETCH_INIT',
    'HEAL_DOWN_CALF_STRETCH',
    'DOUBLE_HEAL_LIFTS_INIT', 
    'DOUBLE_HEAL_LIFTS',
    'TOUCH_TOES_EASY_INIT',
    'TOUCH_TOES_EASY',
    'END'
  ],
  JOG_MEDIUM: [
    'INTRO_JOG_LIGHT',
    'SINGLE_HEAL_LIFTS_INIT',
    'SINGLE_HEAL_LIFTS',
    'LEG_RAISES_INIT',
    'LEG_RAISES',
    'END'
  ],
  JOG_HARD: [
    'INTRO_JOG_LIGHT',
    'DOUBLE_HEAL_LIFTS_INIT', 
    'DOUBLE_HEAL_LIFTS',
    'SINGLE_HEAL_LIFTS_INIT',
    'SINGLE_HEAL_LIFTS',
    'BOTTOM_LIFTS_INIT',
    'BOTTOM_LIFTS',
    'END'
  ],
  SWIM_LIGHT: [
    'INTRO_SWIM_LIGHT',
    'ELBOW_PULL_INIT',
    'ELBOW_PULL',
    'BUTTERFLY_GROIN_STRETCH_INIT',
    'BUTTERFLY_GROIN_STRETCH',
    'END'
  ],
  SWIM_MEDIUM: [
    'INTRO_SWIM_LIGHT',
    'ELBOW_PULL_INIT',
    'ELBOW_PULL',
    'BUTTERFLY_GROIN_STRETCH_INIT',
    'BUTTERFLY_GROIN_STRETCH',
    'END'
  ],
  SWIM_HARD: [
    'INTRO_SWIM_LIGHT',
    'ELBOW_PULL_INIT',
    'ELBOW_PULL',
    'BUTTERFLY_GROIN_STRETCH_INIT',
    'BUTTERFLY_GROIN_STRETCH',
    'END'
  ],
  RUN_LIGHT: [
    'INTRO_RUN_LIGHT',
    'END'
  ],
  RUN_MEDIUM: [
    'INTRO_RUN_MEDIUM',
    'END'
  ],
  RUN_HARD: [
    'INTRO_RUN_HARD',
    'END'
  ],
  SOCCER_LIGHT: [
    'INTRO_SOCCER_LIGHT',
    'END'
  ],
  SOCCER_MEDIUM: [
    'INTRO_SOCCER_LIGHT',
    'END'
  ],
  SOCCER_HARD: [
    'INTRO_SOCCER_LIGHT',
    'END'
  ],
  TENNIS_LIGHT: [
    'INTRO_TENNIS_LIGHT',
    'END'
  ],
  TENNIS_MEDIUM: [
    'INTRO_TENNIS_LIGHT',
    'END'
  ],
  TENNIS_HARD: [
    'INTRO_TENNIS_LIGHT',
    'END'
  ],
  WEGIHTS_LIGHT: [
    'INTRO_WEGIHTS_LIGHT',
    'END'
  ],
  WEGIHTS_MEDIUM: [
    'INTRO_WEGIHTS_LIGHT',
    'END'
  ],
  WEGIHTS_HARD: [
    'INTRO_WEGIHTS_LIGHT',
    'END'
  ],
  GOLF_LIGHT: [
    'INTRO_GOLF_LIGHT',
    'END'
  ],
  GOLF_MEDIUM: [
    'INTRO_GOLF_LIGHT',
    'END'
  ],
  GOLF_HARD: [
    'INTRO_GOLF_LIGHT',
    'END'
  ],
  BASKETBALL_LIGHT: [
    'INTRO_BASKETBALL_LIGHT',
    'END'
  ],
  BASKETBALL_MEDIUM: [
    'INTRO_BASKETBALL_LIGHT',
    'END'
  ],
  BASKETBALL_HARD: [
    'INTRO_BASKETBALL_LIGHT',
    'END'
  ],
  CRICKET_LIGHT: [
    'INTRO_CRICKET_LIGHT',
    'END'
  ],
  CRICKET_MEDIUM: [
    'INTRO_CRICKET_LIGHT',
    'END'
  ],
  CRICKET_HARD: [
    'INTRO_CRICKET_LIGHT',
    'END'
  ],
  BOX_LIGHT: [
    'INTRO_BOX_LIGHT',
    'END'
  ],
  BOX_MEDIUM: [
    'INTRO_BOX_LIGHT',
    'END'
  ],
  BOX_HARD: [
    'INTRO_BOX_LIGHT',
    'END'
  ],
  KAYAK_LIGHT: [
    'INTRO_KAYAK_LIGHT',
    'END'
  ],
  KAYAK_MEDIUM: [
    'INTRO_KAYAK_LIGHT',
    'END'
  ],
  KAYAK_HARD: [
    'INTRO_KAYAK_LIGHT',
    'END'
  ],
  SURF_LIGHT: [
    'INTRO_SURF_LIGHT',
    'END'
  ],
  SURF_MEDIUM: [
    'INTRO_SURF_LIGHT',
    'END'
  ],
  SURF_HARD: [
    'INTRO_SURF_LIGHT',
    'END'
  ],
  FRISBEE_LIGHT: [
    'INTRO_FRISBEE_LIGHT',
    'END'
  ],
  FRISBEE_MEDIUM: [
    'INTRO_FRISBEE_LIGHT',
    'END'
  ],
  FRISBEE_HARD: [
    'INTRO_FRISBEE_LIGHT',
    'END'
  ],
  CYCLE_LIGHT: [
    'INTRO_CYCLE_LIGHT',
    'END'
  ],
  CYCLE_MEDIUM: [
    'INTRO_CYCLE_LIGHT',
    'END'
  ],
  CYCLE_HARD: [
    'INTRO_CYCLE_LIGHT',
    'END'
  ],
  DANCE_LIGHT: [
    'INTRO_DANCE_LIGHT',
    'END'
  ],
  DANCE_MEDIUM: [
    'INTRO_DANCE_LIGHT',
    'END'
  ],
  DANCE_HARD: [
    'INTRO_DANCE_LIGHT',
    'END'
  ],
  GARDEN_LIGHT: [
    'INTRO_GARDEN_LIGHT',
    'END'
  ],
  GARDEN_MEDIUM: [
    'INTRO_GARDEN_LIGHT',
    'END'
  ],
  GARDEN_HARD: [
    'INTRO_GARDEN_LIGHT',
    'END'
  ],
  NETBALL_LIGHT: [
    'INTRO_NETBALL_LIGHT',
    'END'
  ],
  NETBALL_MEDIUM: [
    'INTRO_NETBALL_LIGHT',
    'END'
  ],
  NETBALL_HARD: [
    'INTRO_NETBALL_LIGHT',
    'END'
  ],
  YOGA_LIGHT: [
    'INTRO_YOGA_LIGHT',
    'END'
  ],
  YOGA_MEDIUM: [
    'INTRO_YOGA_LIGHT',
    'END'
  ],
  YOGA_HARD: [
    'INTRO_YOGA_LIGHT',
    'END'
  ],
  PADDLE_BOARD_LIGHT: [
    'INTRO_PADDLE_BOARD_LIGHT',
    'END'
  ],
  PADDLE_BOARD_MEDIUM: [
    'INTRO_PADDLE_BOARD_LIGHT',
    'END'
  ],
  PADDLE_BOARD_HARD: [
    'INTRO_PADDLE_BOARD_LIGHT',
    'END'
  ],
  HIKE_LIGHT: [
    'INTRO_HIKE_LIGHT',
    'END'
  ],
  HIKE_MEDIUM: [
    'INTRO_HIKE_LIGHT',
    'END'
  ],
  HIKE_HARD: [
    'INTRO_HIKE_LIGHT',
    'END'
  ],
  ROCK_CLIMB_LIGHT: [
    'INTRO_ROCK_CLIMB_LIGHT',
    'END'
  ],
  ROCK_CLIMBING_MEDIUM: [
    'INTRO_ROCK_CLIMB_LIGHT',
    'END'
  ],
  ROCK_CLIMBING_HARD: [
    'INTRO_ROCK_CLIMB_LIGHT',
    'END'
  ],
  CROSS_TRAIN_LIGHT: [
    'INTRO_CROSS_TRAIN_LIGHT',
    'END'
  ],
  CROSS_TRAIN_MEDIUM: [
    'INTRO_CROSS_TRAIN_LIGHT',
    'END'
  ],
  CROSS_TRAIN_HARD: [
    'INTRO_CROSS_TRAIN_LIGHT',
    'END'
  ],
  HORSE_RIDE_LIGHT: [
    'INTRO_HORSE_RIDE_LIGHT',
    'END'
  ],
  HORSE_RIDE_MEDIUM: [
    'INTRO_HORSE_RIDE_LIGHT',
    'END'
  ],
  HORSE_RIDE_HARD: [
    'INTRO_HORSE_RIDE_LIGHT',
    'END'
  ],
  SKATE_LIGHT: [
    'INTRO_SKATE_LIGHT',
    'END'
  ],
  SKATE_MEDIUM: [
    'INTRO_SKATE_LIGHT',
    'END'
  ],
  SKATE_HARD: [
    'INTRO_SKATE_LIGHT',
    'END'
  ],
  ARMS: [
    'INTRO_ARMS',
    'END'
  ],
  LOWER_LEGS: [
    'INTRO_LOWER_LEGS',
    'END'
  ],
  UPPER_LEGS: [
    'INTRO_UPPER_LEGS',
    'END'
  ],
  STOMACH: [
    'INTRO_STOMACH',
    'END'
  ],
  CORE_STRENGTH: [
    'INTRO_CORE_STRENGTH',
    'END'
  ],
};

module.exports = routineStore;